// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using network_signal_monitoring.Data;

#nullable disable

namespace network_signal_monitoring.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260527062910_AddLocation")]
    partial class AddLocation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0-preview.5.25277.114")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("network_signal_monitoring.Models.NetworkSignal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("DownloadSpeed")
                        .HasColumnType("double precision");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("NetworkType")
                        .HasColumnType("text");

                    b.Property<string>("SignalStrength")
                        .HasColumnType("text");

                    b.Property<double>("UploadSpeed")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("NetworkSignals");
                });
#pragma warning restore 612, 618
        }
    }
}
